export const HOME = '/'
export const LOGIN = '/login'
export const SIGNUP = '/signup'
export const SEARCH = '/search'
export const PRODUCTPAGE = '/productpage'
export const VERIFYFARMER = '/verifyfarmer'
